name: "Pull Request Labeler"
on: [pull_request]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@0967ca812e7fdc8f5f71402a1b486d5bd061fe20 # v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
