name: "Pull Request Labeler"
on: [pull_request]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@ba790c862c380240c6d5e7427be5ace9a05c754b # v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
