name: "Pull Request Labeler"
on: [pull_request]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@9fcb2c2f5584144ca754f8bfe8c6f81e77753375 # v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
