# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x,24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build -- ngx-darkbox-gallery --configuration=production
      - run: cp *.md dist/ngx-darkbox-gallery/
      - run: cp LICENSE dist/ngx-darkbox-gallery/
      - name: Test
        run: npm run test:lib:ci
      # Upload the build artifacts to GitHub
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ngx-darkbox-gallery-${{ matrix.node-version }}
          path: dist/ngx-darkbox-gallery/
