# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [released]

jobs:
  # Automaticcally extract the release notes from Changelog.md 
  release-notes:
    name: Create release notes
    uses: ./.github/workflows/actions/update-release-notes.yml
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-release:
    name: Build release
    uses: ./.github/workflows/actions/build-release.yml
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: build
    steps:
      - uses: ./.github/workflows/actions/publish-package.yml
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 16
          NPM_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    steps:
      - uses: ./.github/workflows/actions/publish-package.yml
        with:
          registry-url: https://npm.pkg.github.com/
          node-version: 16
          NPM_TOKEN: ${{secrets.npm_token}}
