# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package Next Version

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # renovate: tag=v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --no-optional
      - run: npm run build -- ngx-darkbox-gallery --configuration=production
      - run: cp *.md dist/ngx-darkbox-gallery/
      - run: cp --parents src/assets/* dist/ngx-darkbox-gallery
      - run: cp LICENSE dist/ngx-darkbox-gallery/
      #- run: npm test --if-present
      - uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # renovate: tag=v2
        with:
          name: ngx-darkbox-gallery
          path: dist/ngx-darkbox-gallery/

  build-demo:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2
      - uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60 # renovate: tag=v2
        with:
          name: ngx-darkbox-gallery
          path: dist/ngx-darkbox-gallery/
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # renovate: tag=v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --no-optional
      - run: cd dist/ngx-darkbox-gallery
      - run: npm link
      - run: cd ../..
      - run: npm link @failed-successfully/ngx-darkbox-gallery
      - run: npm run build
      #- run: npm test --if-present
      - uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # renovate: tag=v2
        with:
          name: ngx-darkbox-gallery-demo
          path: dist/ngx-darkbox-gallery-library/

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2
      - uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60 # renovate: tag=v2
        with:
          name: ngx-darkbox-gallery
          path: artifact/ngx-darkbox-gallery/
      - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # renovate: tag=v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci --no-optional
      - run: npm publish --access public --tag next
        working-directory: artifact/ngx-darkbox-gallery
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2
      - uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60 # renovate: tag=v2
        with:
          name: ngx-darkbox-gallery
          path: artifact/ngx-darkbox-gallery/
      - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # renovate: tag=v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci --no-optional
      - run: npm publish --ignore-scripts --tag next
        working-directory: artifact/ngx-darkbox-gallery
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-gh-pages:
    needs: build-demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2
      - uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60 # renovate: tag=v2
        with:
          name: ngx-darkbox-gallery-demo
          path: target/
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # renovate: tag=v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
          keep_files: true
          cname: darkbox.click
