# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --ignore-scripts
      - run: npm run build -- ngx-darkbox-gallery --prod
      - run: cp *.md dist/ngx-darkbox-gallery/
      - run: cp LICENSE dist/ngx-darkbox-gallery/
      #- run: npm test --if-present
      - uses: actions/upload-artifact@v2
        with:
          name: ngx-darkbox-gallery
          path: dist/ngx-darkbox-gallery/

  build-demo:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ngx-darkbox-gallery
          path: dist/ngx-darkbox-gallery/
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --ignore-scripts
      - run: cd dist/ngx-darkbox-gallery
      - run: npm link
      - run: cd ../..
      - run: npm link @failed-successfully/ngx-darkbox-gallery
      - run: npm run build -- --prod
      #- run: npm test --if-present
      - uses: actions/upload-artifact@v2
        with:
          name: ngx-darkbox-gallery-demo
          path: dist/ngx-darkbox-gallery-library/

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ngx-darkbox-gallery
          path: artifact/ngx-darkbox-gallery/
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci --ignore-scripts
      - working-directory: artifact/ngx-darkbox-gallery
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ngx-darkbox-gallery
          path: artifact/ngx-darkbox-gallery/
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci --ignore-scripts
      - working-directory: artifact/ngx-darkbox-gallery
      - run: npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-gh-pages:
    needs: build-demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ngx-darkbox-gallery-demo
          path: target/
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
          cname: darkbox.failedsuccessfully.de
