on:
  workflow_call:
    inputs:
      registry-url:
        required: true
        type: string
      node-version:
        required: true
        type: number
      release-tag:
        required: false
        type: string
    secrets:
      npm-token:
        required: true

jobs:
  release-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3
        with:
          name: ngx-darkbox-gallery
          path: artifact/ngx-darkbox-gallery/
      - uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }}
      - run: npm ci --no-optional
      - run: npm publish --access public ${{ inputs.release-tag }}
        working-directory: artifact/ngx-darkbox-gallery
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
