on:
  workflow_call:

permissions:
  contents: write

jobs:
  update-release-notes:
    name: Update release notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@273da39a24fb7db106a35526c8162815faffd31d # v3
      - name: Update release notes
        id: update-release
        uses: tubone24/update_release@c04c17054b939144ec8a7cba969d74992f812d66 # v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
